<?php
session_start();

// Enable error reporting for debugging
ini_set('display_errors', 1);
error_reporting(E_ALL);

echo "<h1>Test Page</h1>";
echo "<p>This is a simple test page to check PHP, session, and database connectivity.</p>";

// --- 1. Test Session Variables ---
echo "<h2>Session Status:</h2>";
if (isset($_SESSION['user_id'])) {
    echo "<p>Session is active. User ID: " . htmlspecialchars($_SESSION['user_id']) . "</p>";
    if (isset($_SESSION['email'])) {
        echo "<p>User Email: " . htmlspecialchars($_SESSION['email']) . "</p>";
    }
} else {
    echo "<p>No active session found. Please <a href='login.php'>login</a>.</p>";
}

// --- 2. Test Database Connection ---
echo "<h2>Database Connection Test:</h2>";

$servername = "localhost";
$username = "root";
$password = ""; // IMPORTANT: Set your actual database root password here
$dbname = "course_recommender_db";

// Attempt to connect to MySQL
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    echo "<p style='color: red;'>Database Connection failed: " . $conn->connect_error . "</p>";
} else {
    echo "<p style='color: green;'>Database Connection successful!</p>";

    // --- 3. Test a simple query (optional, but good for full test) ---
    echo "<h3>Simple Query Test:</h3>";
    $sql = "SELECT COUNT(*) as total_users FROM users";
    $result = $conn->query($sql);

    if ($result) {
        $row = $result->fetch_assoc();
        echo "<p>Total users in 'users' table: " . htmlspecialchars($row['total_users']) . "</p>";
        $result->free(); // Free result set
    } else {
        echo "<p style='color: red;'>Error executing query: " . $conn->error . "</p>";
    }

    $conn->close(); // Close the database connection
}

echo "<h2>PHP Info:</h2>";
echo "<p>PHP version: " . phpversion() . "</p>";
echo "<p>Server time: " . date('Y-m-d H:i:s') . "</p>";

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            color: #333;
            margin: 20px;
            line-height: 1.6;
        }
        h1, h2, h3 {
            color: #0056b3;
        }
        p {
            margin-bottom: 10px;
        }
        a {
            color: #007bff;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <!-- Content is generated by PHP above -->
</body>
</html>
